### ISSUE TITLE
No database for another games ? (CS 1.6, HL1, etc)

### ISSUE THREAD

**Issue by UnrealKaraulov** [wootguy/pmodels#2]
@wootguy No database support for another games ? (CS 1.6, HL1, etc)

**Comment by wootguy** [comment]
The site can work for any goldsource game but I only care about Sven Co-op. Space is kind of limited too when using github to store model files (~1GB max per repo if I remember correctly).

**Comment by UnrealKaraulov** [comment]
@wootguy only player models, weapon skins not supported ??

**Comment by wootguy** [comment]
The model viewer/thumbnail generator will need an update for that. [It's forked](https://github.com/wootguy/HL_Tools) from Solokiller's HLMV so that feature probably already exists.
