### ISSUE TITLE
[Model Name]miku_neko

### ISSUE THREAD

**Issue by 7UMENGL1aNG** [wootguy/pmodels#3]
![Screenshot 2022-03-03 122515](https://user-images.githubusercontent.com/97338615/156496075-776b2182-d598-4618-bee9-5cf5bdc808c7.png)

https://wootguy.github.io/scmodels/
Internal Name:GFL_Negev.mdl

↓

![Screenshot 2022-03-03 122534](https://user-images.githubusercontent.com/97338615/156496083-f5157b4f-7963-43ab-b7d6-df1efd0e1a69.png)

https://gamebanana.com/mods/316369
Internal Name:Miku_Neko

**Comment by wootguy** [comment]
The "internal name" is stored inside the model and doesn't have to match the file name. The model on gamebanana also has an "internal name" of GFL_Negev.mdl.

![image](https://user-images.githubusercontent.com/12087544/156524913-43972193-2c28-4218-aa84-35df7917c96e.png)

It probably means the modeller took the skeleton from the negev model and put a miku mesh on top of it.

**Comment by 7UMENGL1aNG** [comment]
Thank You.
I want to upload the models I have collected,is there any idea?

**Comment by wootguy** [comment]
I want to add a model uploader here eventually, but for now you need to upload somewhere else like gamebanana or google drive. Send me a link and I'll add the models in the next database update.

**Comment by 7UMENGL1aNG** [comment]
I will compress all the models I have.
Sorry to trouble you,but could you please filter them for invalid/duplicate models?

**Comment by wootguy** [comment]
The `scmodels.py` script automatically filters duplicates, so yeah that's no trouble.

**Comment by 7UMENGL1aNG** [comment]
> The `scmodels.py` script automatically filters duplicates, so yeah that's no trouble.

https://drive.google.com/file/d/1ds8rSjM3_k1thUNoWdAQqXjfEusr45oy/view?usp=sharing

**Comment by wootguy** [comment]
got it, thanks
