### ISSUE TITLE
touhou_reisenudongeininaba is broken and doesn't include sound files in the download

### ISSUE THREAD

**Issue by WSDguy2014** [wootguy/pmodels#4]
I wanted to use that character model (the one with more effort put into it that includes sound files) for planning on playing Sven Co-op during April Fools day.
![image](https://user-images.githubusercontent.com/13905392/218329312-78c61ec5-a314-4010-91c3-2533ed5c2e3f.png)
For some reason, it didn't include sound files in the download.
For reference, I downloaded another player character model file (`cream_custom_s5` | Cream the Rabbit) that also includes sound files, and it actually included sound file contents in the download and works just fine from my testing.
![image](https://user-images.githubusercontent.com/13905392/218329338-96f007e3-8c3e-435c-80df-977e22c6b6e1.png)
The image preview problem is not big of a deal for me, only worried about the player character model itself.
The error text in the console output suggests that the game cannot allow to have such a long file name, displaying as `touhou_reisenudongeini` instead of `touhou_reisenudongeininaba`, causing it to render a default `helmet` player model as a fallback.
Theoretical fix I think is to change the filename to `touhou_reiseninaba` or `touhou_reisnUdngnInaba`.
![image](https://user-images.githubusercontent.com/13905392/218329468-a17aaf7d-30f0-441c-8059-e46f4bd7f4b8.png)
Sound files probably taken from another character model (Nepgear) for reuse on this character model, judging from the internal .mdl filename. Does this means that I have to download another one just for sound files in order to make it work properly along with filename fixing?

**Comment by wootguy** [comment]
Huh I didn't know there was a length limit for loading the model. I thought that only applied to server downloads. I guess I'll shorten it to `touhou_reiseninaba`.

The sounds are missing, even if in the neptune models. I guess people forgot to include the sounds when sharing them or adding to model packs. The Gamebanana pages don't exist anymore, or probably never did, so I don't know where they would be found.

**Comment by wootguy** [comment]
these models were renamed. Most of these were my fault for adding version suffixes.

```
2d_hdn_neppugia-cosplay -> 2d_hdn_neppugia-cos
2d_hdn_neptune-mizugi-c2 -> 2d_hdn_neptune-miz-c2
2d_kancolle_shimakaze_v2 -> 2d_kc_shimakaze_v2
2d_mdn_tenno_uzume-mizugi -> 2d_mdn_tenno-mizugi
2d_mdn_tennouboshi_uzume -> 2d_mdn_tenno_uzume
2d_touhou_flandre_scarlet -> 2d_touhou_scarlet
2d_touhou_izayoi_sakuya -> 2d_touhou_sakuya
2d_touhou_kazami_yuuka_4 -> 2d_touhou_yuuka_4
2d_touhou_konpaku_youmu -> 2d_touhou_youmu
2d_touhou_suikaabcedition -> 2d_touhou_suikaabc
azur_lane_enterprise_v2 -> al_enterprise2_v2
bs_unarmored_barney_1_ld -> bs_barney_1_ld
bs_unarmored_barney_2_ld -> bs_barney_2_ld
bwtgs_sena_kashiwazaki_v2 -> bwtgs_sena_v2
cof_simon_leatherhoff_v2 -> cof_simon_l_v2
cof_simon_psykskallar_v2 -> cof_simon_p_v2
cyborg_ninja_liquidheat -> cyborg_ninja_heat
david_leatherhoff_female -> david_l_female
furry_maid_black2_noglow -> furry_maid_black3
hdn_neppugia-cosplay_v2 -> hdn_neppugia-cos_v2
hdn_neptune-mizugi-c2_v2 -> hdn_neptune-miz-c2_v2
hl2_combine_soldier_prisonguard -> hl2_prisonguard
infected_businessman_v2 -> infected_bman_v2
kfparamedicalfredanderson -> kfparamedic
monogatari_hanekawa_0b_v2 -> mg_hanekawa_0b_v2
monogatari_hanekawa_1b_v2 -> mghanekawa_1b_v2
monogatari_hanekawa_b_v2 -> mghanekawa_b_v2
op4_scientist_einstein_ld -> op4_sci_einstein_ld
op4_scientist_luther_ld -> op4_sci_luther_ld
op4_scientist_walter_ld -> op4_sci_walter_ld
player_multiplayer_model_st -> multiplayer_model_st
re_succ_citizen_unit_v2 -> res_citizen_v2
re_succ_combat_response_unit -> res_combat_resp
re_succ_combat_technician -> res_combat_tech
re_succ_commander_merc_v2 -> res_commander_merc_v2
re_succ_corporal_gote_v2 -> res_corp_gote_v2
re_succ_major_lie_rick_v2 -> res_major_lie_rick_v2
re_succ_marksman_unit_v2 -> res_marksman_v2
re_succ_operator_unit_v2 -> res_operator_v2
re_succ_security_unit_v2 -> res_security_v2
re_succ_security_unita_v2 -> res_securitya_v2
re_succ_security_unitb_v2 -> res_securityb_v2
re_succ_security_unitc_v2 -> res_securityc_v2
rvi_bs_unarmored_barney_1 -> rvi_bs_barney_1
rvi_bs_unarmored_barney_2 -> rvi_bs_barney_2
sister_mary_ellie_fant_v2 -> mary_ellie_fant_v2
sonic_forces_classic_c_v2 -> sonicf_classic_c_v2
sonic_forces_classic_c_v3 -> sonicf_classic_c_v3
sonic_forces_classic_v2 -> sonicf_classic_v2
sonic_forces_classic_v3 -> sonicf_classic_v3
spess_kagerou_sweater_v2 -> spess_kagerou2_v2
stalker_freedomantigas_v2 -> stalker_freedomagas_v2
stalker_lonerantigas_v2 -> stalker_loneragas_v2
stalker_monolithantigas -> stalker_monoagas
stalker_monolithseva_v2 -> stalker_monoseva_v2
ta_c_elite_color_armor2 -> ta_c_elite_c_armor2
ta_c_s_advisor_armor2_v2 -> ta_c_s_advisor3_v2
ta_c_s_advisor_armor_v2 -> ta_c_s_advisor4_v2
ta_c_s_arctic_armor2_v2 -> ta_c_s_arctic3_v2
ta_c_s_arctic_armor_v2 -> ta_c_s_arctic4_v2
ta_c_shadow-3_armor2_v2 -> ta_c_shadow-3_a2_v2
tc_alternative-dr.kleiner -> tc_alt-dr.kleiner
touhou_izayoi_sakuya_v2 ->  -> touhou_sakuya_v2
touhou_kagerou_bikini_v2 -> touhou_kagerou2_v2
touhou_kochiya_sanae_v2 -> touhou_k_sanae_v2
touhou_reisenudongeininaba -> touhou_reisen2
touhou_yakumo_yukari_v2 -> touhou_yukari_v2
vehicleshit_m1a1_abrams -> vehicleshit_abrams
vinnie_gognitti_alt_clean -> vinnieg_alt_clean
vinnie_gognitti_plain_clean -> vinnieg_plain_clean
vocaloid_yukari-yuzuki_v2 -> vocaloid_yukari_v2
```
